export const interestTags = [
  { name: 'Cooking' },
  { name: 'Travel' },
  { name: 'Photography' },
  { name: 'Hiking' },
  { name: 'Painting' },
  { name: 'Gaming' },
  { name: 'Reading' },
  { name: 'Yoga' },
  { name: 'Music' },
  { name: 'Gardening' },
  { name: 'Fitness' },
  { name: 'Movies' },
  { name: 'Dancing' },
  { name: 'Sports' },
  { name: 'Technology' },
  { name: 'Fashion' },
  { name: 'Foodie' },
  { name: 'Pets' },
  { name: 'Meditation' },
  { name: 'Writing' },
  { name: 'Volunteering' },
  { name: 'Astronomy' },
  { name: 'History' },
  { name: 'Woodworking' },
  { name: 'Art' },
  { name: 'Nature' },
  { name: 'Science' },
  { name: 'Crafting' },
  { name: 'Camping' },
  { name: 'DIY' },
  { name: 'Languages' },
  { name: 'Surfing' },
  { name: 'Fishing' },
  { name: 'Wine Tasting' },
  { name: 'Coffee' },
  { name: 'Running' },
  { name: 'Skiing' },
  { name: 'Snowboarding' },
  { name: 'Philosophy' },
  { name: 'Comedy' },
  { name: 'Health' },
  { name: 'Architecture' },
  { name: 'Board Games' },
  { name: 'Anime' },
  { name: 'Biking' },
  { name: 'Fashion Design' },
  { name: 'Traveling' },
  { name: 'Collecting' },
  { name: 'Film' },
  { name: 'Vintage' },
];
