version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    # volumes:
    #   - ~/apps/postgres:/var/lib/postgresql/data
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=mdp
      - POSTGRES_USER=chak
      - POSTGRES_DB=matcha_db