export const bioMale = [
  '',
  '',
  '',
  'Explorateur de la vie passionné par les aventures spontanées. Toujours partant pour découvrir de nouveaux endroits, de nouvelles cultures et de nouvelles expériences. Adepte du yoga, amateur de cuisine du monde et passionné de photographie.',
  "Ingénieur le jour, guitariste la nuit. Passionné de musique, de concerts et de créativité. À la recherche d'une partenaire pour partager ma passion et peut-être créer de la magie musicale ensemble.",
  "Entrepreneur ambitieux avec une passion pour le fitness. Fan de musculation et de sports extrêmes, mais aussi amateur de moments chill devant un bon film. À la recherche d'une personne équilibrée pour partager des rires et des aventures.",
  "Artiste dans l'âme, je trouve l'inspiration dans chaque coin de la vie. Peintre, sculpteur, et amateur d'art moderne. Recherche une muse pour partager des moments créatifs et explorer le monde artistique ensemble.",
  "Voyageur intrépide en quête de sa prochaine destination. Que ce soit un trek dans l'Himalaya ou une escapade citadine, j'aime explorer et découvrir de nouvelles cultures. Cherche une compagne de voyage pour partager ces aventures.",
  "Épicurien passionné par la gastronomie. En dehors de la cuisine, je suis un cinéphile averti et un amoureux de la nature. À la recherche de quelqu'un pour partager de délicieux repas, des soirées cinéma et des promenades romantiques.",
  "Scientifique en journée, astronome amateur la nuit. Fasciné par l'univers, les étoiles et les mystères de la vie. Cherche une partenaire pour explorer l'infini et au-delà, tout en appréciant les petites choses de la vie quotidienne.",
  "Athlète passionné par les sports extrêmes. Que ce soit le surf, le snowboard ou l'escalade, j'aime l'adrénaline. En dehors de cela, je suis un lecteur assidu et un amateur de musique alternative. Recherche une âme aventureuse pour partager des défis et des moments de détente.",
  "Ingénieur du son et passionné de musique électronique. En quête de nouveaux sons et d'expériences audio uniques. Cherche quelqu'un qui partage la passion pour la musique et qui aime danser toute la nuit.",
  "Amoureux de la technologie et entrepreneur dans l'âme. Toujours à la recherche de nouvelles idées et de projets passionnants. Fan de jeux vidéo, de science-fiction et de voyages intergalactiques. Recherche une partenaire pour conquérir le monde numérique et réel.",
  'Prince charmant moderne en quête de sa princesse. Passionné par les couchers de soleil, les roses rouges et les serenades sous la pleine lune. Prêt à vous faire tourner la tête avec des compliments doux et des gestes romantiques.',
  "Chevalier moderne cherchant sa dame de cœur. Prêt à conquérir votre monde avec des gestes galants, des aventures extraordinaires et des déclarations d'amour dignes des contes de fées.",
  "Artiste romantique avec une passion pour les déclarations grandioses. Imaginez des poèmes d'amour, des dîners aux chandelles et des escapades surprise. Prêt à transformer chaque jour en une aventure romantique.",
  "Explorateur passionné du territoire de l'amour. Armé de sourires radieux, de compliments charmants et de l'espoir éternel. Cherche une coéquipière pour une expédition romantique vers le bonheur infini.",
  "Rêveur insatiable avec un amour pour les clichés romantiques. Convaincu que chaque histoire d'amour devrait commencer par un regard intense et se terminer par un 'ils vécurent heureux pour toujours'. Prêt à écrire notre conte de fées.",
  'Amoureux de la vie avec un penchant pour le glamour. Imaginez des soirées de gala, des danses élégantes et des déclarations enflammées. Prêt à vous traiter comme la star de votre propre film romantique.',
  "Cavalier servant de l'amour moderne. Prêt à vous surprendre avec des cadeaux exquis, des dîners aux chandelles et des promenades romantiques sous la lueur des étoiles. Cherche une dame pour partager ces moments magiques.",
  'Gentleman moderne avec un penchant pour les gestes chevaleresques. Prêt à ouvrir des portes, tirer des chaises et vous traiter avec le respect que vous méritez. Cherche une dame qui apprécie la vieille école du romantisme.',
  "Architecte de l'amour avec un design impeccable. Imaginez des châteaux en nuages, des ponts d'affection et des jardins secrets. Prêt à construire une relation digne d'une éternité enchantée.",
  "Adorateur des étoiles cherchant sa muse. Convaincu que chaque étoile du ciel a une histoire à raconter et que la nôtre devrait être la plus belle. Prêt à créer des constellations d'amour qui illumineront nos nuits.",
];

export const bioFemale = [
  '',
  '',
  '',
  "Rêveuse à la recherche de complicité. Amoureuse de la nature, je trouve la paix dans une promenade en forêt ou au bord de la mer. Adepte de la danse, de la musique et des soirées cosy devant une bonne série. À la recherche d'une connexion profonde et de moments magiques.",
  "Artiste créative avec une passion pour la photographie. Mon appareil photo est mon compagnon constant lors de mes aventures. Fan de musées, de galeries d'art et de cafés artistiques. Recherche un partenaire pour explorer le monde à travers l'objectif et créer des souvenirs durables.",
  "Entrepreneure ambitieuse qui jongle entre le monde des affaires et la passion pour le bien-être. Amateur de yoga, de méditation et de cuisine saine. À la recherche d'une âme sœur pour partager des moments de croissance personnelle et de bonheur.",
  "Danseuse passionnée qui trouve l'expression à travers le mouvement. En dehors du studio de danse, je suis une amatrice de littérature classique et une voyageuse curieuse. Recherche quelqu'un pour partager des pas de danse et des conversations intellectuelles.",
  "Esprit libre cherchant son âme sœur. Adepte du camping, de la randonnée et des cieux étoilés. Passionnée d'écriture créative et de poésie. À la recherche d'une connexion authentique avec quelqu'un qui partage une passion pour l'aventure et la créativité.",
  "Fanatique de la mode et passionnée par l'industrie créative. Que ce soit la haute couture ou le vintage, j'aime exprimer ma créativité à travers mes tenues. Amateur de café et de conversations profondes. À la recherche d'un compagnon de style et d'une connexion intellectuelle.",
  "Professionnelle passionnée qui trouve l'équilibre entre carrière et plaisir. En dehors du bureau, je suis une amatrice de vin, de cuisine raffinée et de voyages exotiques. Recherche un partenaire pour partager des soirées élégantes et des moments de détente.",
  "Aventurière citadine qui aime explorer les rues animées et les recoins cachés de la ville. Fan de musique indie, de cinéma en plein air et de soirées avec des amis. Recherche quelqu'un pour partager des escapades urbaines et des moments de légèreté.",
  "Romantique dans l'âme à la recherche d'une histoire d'amour intemporelle. Passionnée par la littérature romantique, les films classiques et les dîners aux chandelles. Recherche un partenaire pour partager des moments doux et des rêves éternels.",
  "Ingénieure créative avec une passion pour la technologie. Toujours à la pointe de l'innovation, mais apprécie aussi les moments simples de la vie. Amateur de jeux vidéo, de musique électronique et de brunchs du dimanche. À la recherche d'une connexion authentique dans ce monde numérique.",
  "Princesse moderne cherchant son prince charmant. Passionnée par les contes de fées, les robes étincelantes et les baisers magiques. Prête à vous emmener dans un monde enchanté où l'amour règne en maître.",
  "Fée moderne avec une baguette magique et un amour pour les histoires d'amour éternelles. Prête à répandre des étoiles scintillantes et à réaliser vos vœux les plus romantiques.",
  "Diva romantique avec un penchant pour le théâtre de l'amour. Imaginez des scènes d'émotion intense, des baisers passionnés et des déclarations dignes des plus grandes histoires d'amour de l'écran argenté.",
  "Artiste du cœur avec une palette d'émotions infinie. Prête à peindre des toiles d'amour vibrantes, à composer des poèmes enflammés et à danser au rythme de la musique du bonheur.",
  "Étoile filante cherchant son ciel étoilé. Convaincue que chaque histoire d'amour devrait commencer par un vœu fait aux étoiles. Prête à créer des constellations d'amour qui brilleront pour toujours.",
  "Déesse de l'amour avec un trône de romantisme. Prête à régner sur un royaume où l'affection est la monnaie et les sourires sont la couronne. Cherche un chevalier prêt à conquérir son cœur royal.",
  "Sirène romantique avec une voix enchanteresse. Prête à séduire avec des mélodies d'amour, des danses gracieuses et des étreintes dignes des profondeurs de l'océan de l'amour.",
  "Romantique incurable avec une collection de rêves. Prête à créer un musée de moments doux, de souvenirs magiques et d'aventures dignes d'un livre de contes. Cherche un partenaire pour partager l'histoire de sa vie.",
  "Reine du bonheur avec un trône de douceur. Prête à régner sur un royaume où les rires sont la loi suprême et les câlins sont la monnaie d'échange. Cherche un roi prêt à partager son royaume de bonheur éternel.",
  "Artisane de l'amour avec une boîte à outils pleine de gestes doux. Prête à construire une maison de bonheur, à tisser des rêves d'amour et à peindre des sourires sur les visages. Cherche un partenaire pour créer une œuvre d'art d'amour infini.",
];
