export const jobs = [
  'Développeur web',
  'Infirmier/infirmière',
  'Enseignant/enseignante',
  'Ingénieur logiciel',
  'Médecin',
  'Architecte',
  'Avocat/avocate',
  'Chef cuisinier/chef cuisinière',
  'Artiste peintre',
  'Journaliste',
  'Pompier/pompière',
  'Photographe',
  'Electricien/électricienne',
  'Plombier/plombière',
  'Psychologue',
  'Agent immobilier/agent immobilière',
  'Astronaute',
  'Vétérinaire',
  'Acteur/actrice',
  'Scientifique',
  'Athlète',
  'Garde forestier/garde forestière',
  'Traducteur/traductrice',
  'Agent de police',
  'Chef de projet',
  'Designer graphique',
  'Secrétaire',
  'Chauffeur de taxi',
  'Infirmier vétérinaire',
  'Conseiller financier/conseillère financière',
  'Chirurgien/chirurgienne',
  'Agent de voyages',
  'Sapeur-pompier forestier/sapeuse-pompière forestière',
  'Maquilleur/maquilleuse',
  'Pharmacien/pharmacienne',
  'Chauffeur de camion',
  'Expert-comptable/experte-comptable',
  'Agent de sécurité',
  'Danseur/danseuse',
  'Géologue',
  'Électricien automobile/électricienne automobile',
  'Agent de bord',
  "Décorateur/décoratrice d'intérieur",
  "Gardien/gardienne d'animaux",
  'Opticien/opticienne',
  'Agriculteur/agricultrice',
  'Sculpteur/sculptrice',
  'Conducteur/conductrice de train',
  'Diététicien/diététicienne',
  'Pilote de ligne',
  'Écrivain/écrivaine',
  'Ingénieur civil/ingénieure civile',
  'Agent de voyages',
  'Chercheur/chercheuse',
  'Conseiller/conseillère en marketing',
  'Maçon/maçonne',
  'Analyste financier/analyste financière',
  'Directeur/directrice artistique',
  'Consultant/consultante en RH',
  "Pilote d'hélicoptère",
  'Psychiatre',
  'Designer de jeux vidéo',
  'Inspecteur/inspectrice de police',
  'Chercheur en biologie',
  'Spécialiste en intelligence artificielle',
  'Mécanicien/mécanicienne automobile',
  'Maquettiste',
  'Conducteur/conductrice de bus',
  'Pilote de course',
  'Urbaniste',
  'Chirurgien dentiste',
  'Concepteur/conceptrice de logiciels',
  'Paysagiste',
  'Orthophoniste',
  'Ingénieur aérospatial/ingénieure aérospatiale',
  'Réalisateur/réalisatrice de films',
  'Traducteur/traductrice littéraire',
  'Géographe',
  'Décorateur/décoratrice de gâteaux',
  'Chargé/chargée de communication',
  'Électricien/électricienne naval(e)',
  'Technicien/technicienne en radiologie',
  'Directeur/directrice de la photographie',
  'Artisan/artisane bijoutier/bijoutière',
  'Responsable des achats',
  'Animateur/animatrice radio',
  'Agent de maintenance informatique',
  'Ingénieur en génie civil',
  'Graphiste',
  'Économiste',
  'Biologiste marin/biologiste marine',
  'Danseur/danseuse de ballet',
  'Agent immobilier commercial/agent immobilière commerciale',
  'Instructeur/instructrice de yoga',
  'Analyste de données',
  'Responsable des ressources humaines',
  'Physiothérapeute',
  'Ingénieur/ingénieure en robotique',
  'Viticulteur/viticultrice',
  'Parfumeur/parfumeuse',
];
