export const studies = [
  'Informatique',
  'Médecine',
  'Droit',
  'Art et design',
  'Biologie',
  'Ingénierie logicielle',
  'Psychologie',
  'Éducation',
  'Génie civil',
  'Sciences politiques',
  'Physique',
  'Chimie',
  'Architecture',
  "Sciences de l'environnement",
  'Marketing',
  'Sociologie',
  "Histoire de l'art",
  'Génie électrique',
  'Langues étrangères',
  'Mathématiques',
  'Géographie',
  'Philosophie',
  'Gestion des affaires',
  'Musique',
  'Journalisme',
  'Génie mécanique',
  'Économie',
  'Relations internationales',
  'Anthropologie',
  'Sciences informatiques',
  'Biotechnologie',
  'Études cinématographiques',
  'Relations publiques',
  'Génie aérospatial',
  'Études religieuses',
  'Génie chimique',
  'Communication',
  'Design graphique',
  'Études de genre',
  'Études de la santé',
  'Astrophysique',
  'Informatique quantique',
  'Génie biomédical',
  'Linguistique',
  'Éthique et droit des affaires',
  'Géologie',
  'Études de développement',
  'Ingénierie des matériaux',
  'Études du théâtre',
  "Sciences de l'alimentation",
  'Neurosciences',
  'Marketing digital',
  'Énergies renouvelables',
  'Études maritimes',
  'Urbanisme',
  'Études médiévales',
  'Génie industriel',
  'Études de la mode',
  'Génie nucléaire',
  'Études de la sécurité informatique',
  "Études de l'enfance",
  'Génie ferroviaire',
  'Gestion des catastrophes',
  'Études de la mer',
  'Génie pétrolier',
  'Études urbaines',
  'Génie des transports',
  'Études sur la paix',
  'Gestion des opérations',
  'Études sur le vieillissement',
  'Gestion des données',
  'Études sur la diversité culturelle',
  'Génie des télécommunications',
  'Études du patrimoine',
  'Génie forestier',
  "Études de l'efficacité énergétique",
  'Génie des mines',
  'Études du tourisme',
  'Génie spatial',
  'Études des médias',
  'Génie de la construction',
  'Études de la consommation',
  'Génie des procédés',
  'Études de la gestion de projet',
  'Génie mécatronique',
  'Études sur la famille',
  'Génie acoustique',
  'Études de la durabilité',
  "Génie de l'eau",
  "Études de l'art numérique",
  'Gestion des RH',
  'Études de la bioéthique',
  'Génie textile',
  'Études sur la mondialisation',
  'Génie de la robotique',
  'Études sur la criminalistique',
  'Génie agricole',
  "Études de la qualité de l'air",
  'Génie des systèmes',
];
